name: deployment_pipeline
on:
  workflow_dispatch
    # push:
    #     branches:
    #         - main
    # pull_request:
    #     branches: [main]
    #     types: [opened, synchronize]

jobs:
    simple_deployment_pipeline:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.12'
                cache: 'pip'
            - uses: actions/setup-node@v4
              with:
              # Version Spec of the version to use in SemVer notation.
              # It also emits such aliases as lts, latest, nightly and canary builds
              # Examples: 12.x, 10.15.1, >=10.15.0, lts/Hydrogen, 16-nightly, latest, node
                node-version: '20'
            - name: build node dependencies
              run: cd js_css && npm install && npm run build && rm -rf node_modules
            - name: Install PY requirements
              run: pip install -r requirements.txt
            - name: Run unittests
              run: pytest


              
            # - name: Start server
            #   run: python manage.py runserver


