name: deployment_pipeline
on:
  workflow_dispatch
    # push:
    #     branches:
    #         - main
    # pull_request:
    #     branches: [main]
    #     types: [opened, synchronize]

jobs:
    simple_deployment_pipeline:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.12'
                cache: 'pip'
            - name: Display Python version
              run: pip install -r requirements.txt
            - name: Start server
              run: python manage.py runserver

